### ISSUE TITLE
Error connecting to API (403 Forbidden)

### ISSUE THREAD

**Issue by suhaasprasad** [dgreif/homebridge-hatch-baby-rest#101]
Got this error after installing the homebridge-hatch-baby-rest v4.0.0 plugin via Homebridge UI

Here's my system information:
OS	Raspbian GNU/Linux Buster (10)
Hostname	raspberrypi
IPv4 (eth0)	192.168.1.180
IPv6 (eth0)	2600:1700:4a30:1aa0::b
Node.js Version	v18.13.0
User	homebridge
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules
Service Mode	Yes

Here are the logs:
```[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] Request to https://data.hatchbaby.com/service/app/iotDevice/v2/fetch?iotProducts=restPlus&iotProducts=riot&iotProducts=riotPlus&iotProducts=restMini&iotProducts=restore failed
[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] Error connecting to API
[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1677438141138,
    socket: 1677438141144,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: 1677438141145,
    response: 1677438141174,
    end: 1677438141177,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 6,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: NaN,
      firstByte: 29,
      download: 3,
      total: 39
    }
  }
}
[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] Request to https://data.hatchbaby.com/service/app/restPlus/token/v1/fetch failed
[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] Failed to Create an MQTT Client
[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1677438141138,
    socket: 1677438141144,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: 1677438141145,
    response: 1677438141198,
    end: 1677438141199,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 6,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: NaN,
      firstByte: 53,
      download: 1,
      total: 61
    }
  }
}
[2/26/2023, 11:02:21 AM] [homebridge-hatch-baby-rest] Request to https://data.hatchbaby.com/service/app/v2/member failed```

**Comment by dgreif** [comment]
Not sure I've seen this before. Is it possible you entered your username/password incorrectly?

**Comment by suhaasprasad** [comment]
Should've known that was the issue.. thanks!
