### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by HammerAce42** [dgreif/homebridge-hatch-baby-rest#13]
I updated to v2.0 of the plugin earlier and started seeing this error. I uninstalled and reinstalled (in the interim I think you rolled back the version to 1.3.1?) and the error still persists. Here is what I am seeing in the log file.

```
[4/6/2020, 1:48:18 PM] ERROR LOADING PLUGIN homebridge-hatch-baby-rest:
[4/6/2020, 1:48:18 PM] Error: Cannot find module '/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/binding.node'
Require stack:
- /homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/bluetooth-hci-socket/index.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/hci.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/bindings.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/resolve-bindings.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/index.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/lib/hatch-baby-rest.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/lib/accessories/hatch-baby-rest.js
- /homebridge/node_modules/homebridge-hatch-baby-rest/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/hci.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
[4/6/2020, 1:48:18 PM] ====================
```

**Comment by dgreif** [comment]
Do you have a Rest+?  If so, try version `2.0.1`

**Comment by HammerAce42** [comment]
That fixed it. Thanks!
