### ISSUE TITLE
Error at startup: EAFNOSUPPORT, Address family not supported by protocol

### ISSUE THREAD

**Issue by FlipABit** [dgreif/homebridge-hatch-baby-rest#25]
I installed `v2.0.4`, configured it through Homebridge UI and after Homebridge restarted it won't boot back up because of the error below:

```
Error: EAFNOSUPPORT, Address family not supported by protocol                               
    at new Hci (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/h
ci.js:74:18)                                                                                                        
    at new NobleBindings (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hc
i-socket/bindings.js:25:15)                                                                                         
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/h
ci-socket/bindings.js:546:18)                                                                                       
    at Module._compile (internal/modules/cjs/loader.js:1133:30)                                                     
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)                                       
    at Module.load (internal/modules/cjs/loader.js:977:32)                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)                                                
    at Module.require (internal/modules/cjs/loader.js:1019:19)                                                      
    at require (internal/modules/cjs/helpers.js:77:18)                                                              
    at module.exports (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/resol
ve-bindings.js:13:12)                                                                                               
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/index
.js:2:49)                                                                                                           
    at Module._compile (internal/modules/cjs/loader.js:1133:30)                                                     
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)                                       
    at Module.load (internal/modules/cjs/loader.js:977:32)                                                          
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)                                                
    at Module.require (internal/modules/cjs/loader.js:1019:19)                                                      
    at require (internal/modules/cjs/helpers.js:77:18)                                                              
    at new HatchBabyRest (/homebridge/node_modules/homebridge-hatch-baby-rest/lib/hatch-baby-rest.js:30:22)         
    at new HatchBabyRestAccessory (/homebridge/node_modules/homebridge-hatch-baby-rest/lib/accessories/hatch-baby-re
st.js:20:20)                                                                                                        
    at /usr/local/lib/node_modules/homebridge/src/server.ts:357:50                                                  
    at Array.forEach (<anonymous>)                                                                                  
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src
```

**Comment by dgreif** [comment]
What device are you running homebridge on? Does it have Bluetooth LE support?

**Comment by FlipABit** [comment]
I think the confusion came from the install setup via the Homebridge web UI. As soon as the plugin is installed, Homebridge pops up the configuration UI for the plugin, except the configuration looks like it's for the Rest (not Rest+ w/wifi), but that's not obvious. So the MAC address was for the Rest+. Removing that config and adding the username/pass config manually fixed it. That being said, it'd be nice if a bad MAC address or connectivity issue like this didn't crash all of homebridge.

Also, is it possible to set the default audio on the Rest+ like with the bluetooth Rest? It looks like it may be technically possible in the code for both, but I'm unclear what that configuration looks like.

**Comment by dgreif** [comment]
Closing due to inactivity
