### ISSUE TITLE
Error After Adding Hatch Rest

### ISSUE THREAD

**Issue by olimeca** [dgreif/homebridge-hatch-baby-rest#52]
After configuring Hatch Rest with Name and MAC Address the following error is shown after Homebridge restart.

[6/15/2021, 11:11:43 AM] [HatchBabyRest] Error connecting to API
[6/15/2021, 11:11:43 AM] [HatchBabyRest] Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80:18)
    at new NobleBindings (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at module.exports (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/index.js:2:51)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: 97,
  code: 'EAFNOSUPPORT',
  syscall: 'socket'
}

**Comment by olimeca** [comment]
System does not support Bluetooth LE which probably explains it. Closing issue.
