### ISSUE TITLE
Difficulty installing on Docker

### ISSUE THREAD

**Issue by jtermi03** [dgreif/homebridge-hatch-baby-rest#87]
Hi, I'm installing your plugin on a fresh Docker image of Homebridge but running into an issue. After installing the plugin, entering my info in the wizard, and restarting homebridge, Homebridge fails with this error:

```
/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/hci.js:121
      this._socket.bindRaw(this._deviceId);
                   ^
Error: ENODEV, No such device
    at Hci.init (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/hci.js:121:20)
    at NobleBindings.init (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13)
    at Noble.get (/homebridge/node_modules/homebridge-hatch-baby-rest/node_modules/@abandonware/noble/lib/noble.js:73:26)
    at Rest.<anonymous> (/homebridge/node_modules/homebridge-hatch-baby-rest/lib/rest.js:71:138)
    at Generator.next (<anonymous>)
    at /homebridge/node_modules/homebridge-hatch-baby-rest/lib/rest.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/homebridge/node_modules/homebridge-hatch-baby-rest/lib/rest.js:9:12)
    at Rest.getPeripheralByAddress (/homebridge/node_modules/homebridge-hatch-baby-rest/lib/rest.js:69:16)
    at new Rest (/homebridge/node_modules/homebridge-hatch-baby-rest/lib/rest.js:34:39)
```

I've validated I'm using the correct device information, I'm not using a bluetooth Hatch, any idea of what I can try?

**Comment by dgreif** [comment]
https://www.npmjs.com/package/@abandonware/noble#linux is the best set of instructions available for getting this to install properly on different operating systems
